name: fsuae
version: '2.8.3'
summary: FS-UAE Amiga Emulator
description: |
  FS-UAE integrates the most accurate Amiga emulation code available from WinUAE.
  FS-UAE emulates A500, A500+, A600, A1200, A1000, A3000 and A4000 models, but you
  can tweak the hardware configuration and create customized Amigas

grade: stable
confinement: strict

apps:
  fs-uae:
    command: desktop-launch fs-uae
    plugs: [desktop, desktop-legacy, x11, joystick, pulseaudio, home, opengl]
  launcher:
    command: desktop-launch python3 $SNAP/bin/fs-uae-launcher
    plugs: [desktop, desktop-legacy, x11, joystick, pulseaudio, network, home, opengl]

parts:
  fs-uae:
    source: https://fs-uae.net/stable/2.8.3/fs-uae-2.8.3.tar.gz
    plugin: autotools
    build-packages:
      - g++
      - gettext
      - glee-dev
      - libglew-dev
      - libfreetype6-dev
      - libglib2.0-dev
      - libmpeg2-4-dev
      - libopenal-dev
      - libsdl2-dev
      - libxi-dev
      - zip
    prime:
      - -share/applications
      - -share/doc
    after:
      - desktop-qt5
    install: |
      echo Stripping executables
      strip $SNAPCRAFT_PART_INSTALL/bin/* > /dev/null || /bin/true

  launcher:
    source: https://fs-uae.net/stable/2.8.3/fs-uae-launcher-2.8.3.tar.gz
    plugin: make
    stage-packages:
      - python3-pkg-resources
      - python3-pyqt5
      - python3-pyqt5.qtopengl
    after:
      - desktop-qt5
    organize:
      usr/local/share/*: share/
      usr/local/bin/*: bin/
    prime:
      - -usr/local
      - -usr/include
      - -usr/share/apport
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/libthai
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
      - -var

  desktop-qt5:
    prime:
      - -usr/include
      - -usr/share/apport
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/libthai
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
      - -var
