name: fsuae
version: '3.0.2'
summary: FS-UAE Amiga Emulator
description: |
  FS-UAE integrates the most accurate Amiga emulation code available from WinUAE.
  FS-UAE emulates A500, A500+, A600, A1200, A1000, A3000 and A4000 models, but you
  can tweak the hardware configuration and create customized Amigas

grade: stable
confinement: strict
base: core18

apps:
  fs-uae:
    command: desktop-launch fs-uae
    plugs: [desktop, wayland, desktop-legacy, x11, joystick, pulseaudio, home, opengl]
  launcher:
    command: desktop-launch startlauncher
    plugs: [desktop, wayland, desktop-legacy, x11, joystick, pulseaudio, network, home, opengl]

parts:
  patches:
    source: patches
    plugin: dump
    prime:
      - -*

  fs-uae:
    source: https://fs-uae.net/stable/3.0.2/fs-uae-3.0.2.tar.gz
    plugin: autotools
    build-packages:
      - g++
      - gettext
      - glee-dev
      - libglew-dev
      - libfreetype6-dev
      - libglib2.0-dev
      - libmpeg2-4-dev
      - libopenal-dev
      - libsdl2-dev
      - libxi-dev
      - zip
    stage-packages:
      - libopenal1
      - libsdl2-2.0-0
      - libmpeg2-4
    prime:
      - -share/applications
      - -share/doc
    after:
      - patches
      - desktop-qt5
    override-build: |
      echo Applying use-snap-common-dir-fsuae.diff
      patch -p1 < $SNAPCRAFT_STAGE/use-snap-common-dir-fsuae.diff
      snapcraftctl build
      echo Stripping executables
      strip $SNAPCRAFT_PART_INSTALL/bin/* > /dev/null || /bin/true

  launcher:
    source: https://fs-uae.net/stable/3.0.2/fs-uae-launcher-3.0.2.tar.gz
    plugin: make
    build-packages:
      - python3-distutils
    stage-packages:
      - python3-distutils
      - python3-pkg-resources
      - python3-pyqt5
      - python3-pyqt5.qtopengl
      - python3-requests
    after:
      - patches
      - desktop-qt5
    organize:
      usr/local/share/*: share/
      usr/local/bin/*: bin/
    prime:
      - -usr/local
      - -usr/include
      - -usr/share/apport
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/libthai
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
      - -var
    override-build: |
      echo Applying use-snap-common-dir-launcher.diff
      patch -p1 < $SNAPCRAFT_STAGE/use-snap-common-dir-launcher.diff
      snapcraftctl build

  startlauncher:
    source: .
    plugin: dump
    organize:
      startlauncher: bin/

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - dpkg-dev
      - qtbase5-dev
    stage-packages:
      - adwaita-icon-theme
      - dmz-cursor-theme
      - gnome-themes-standard
      - libxkbcommon0
      - light-themes
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
      - shared-mime-info
      - ttf-ubuntu-font-family
      - qtwayland5
      - xdg-user-dirs
